import type { DomainId, Misconception } from '../types';

/**
 * Kataloget over typiske misforståelser.
 *
 * Det er ikke pynt: når eleven rammer den samme fejl to gange, stopper
 * motoren progressionen og kører en målrettet forklaring herfra i stedet
 * for bare at give en ny opgave af samme slags.
 */
const defs: [string, DomainId, string, string, string, string][] = [
  // id, emne, navn, "eleven tror", rettelse, huskeregel

  /* Tal og regning */
  ['regnehierarki-venstre', 'tal', 'Regner fra venstre mod højre',
    'At man bare tager regnestykket i den rækkefølge det står.',
    'Gange og division kommer før plus og minus, uanset rækkefølgen på papiret.',
    'Parenteser → potenser → gange/dividere → plus/minus.'],
  ['negativ-dobbelt-minus', 'tal', 'To minusser i træk',
    'At −(−3) stadig er −3.',
    'Minus foran en parentes vender fortegnet på alt indeni. To minusser bliver til plus.',
    'Minus gange minus giver plus.'],
  ['negativ-multiplikation', 'tal', 'Fortegn ved gange og dividere',
    'At fortegnet er ligegyldigt, eller at to negative tal giver et negativt svar.',
    'Ens fortegn giver plus, forskellige fortegn giver minus.',
    '(−)·(−) = +   og   (−)·(+) = −'],
  ['afrunding-altid-ned', 'tal', 'Runder altid ned',
    'At man skærer cifrene væk i stedet for at runde.',
    'Er cifret efter 5 eller derover, runder man op.',
    '0–4 ned, 5–9 op.'],

  /* Brøker */
  ['broek-add-naevnere', 'broeker', 'Lægger nævnerne sammen',
    'At 1/2 + 1/3 = 2/5.',
    'Nævneren fortæller hvor store stykkerne er. Kun når stykkerne er lige store, kan man lægge tællerne sammen.',
    'Fælles nævner først — derefter kun tællerne.'],
  ['broek-gange-kryds', 'broeker', 'Ganger på kryds',
    'At man krydsganger når man skal gange to brøker.',
    'Ved multiplikation ganger man tæller med tæller og nævner med nævner. Krydsning hører til når man sammenligner brøker.',
    'Tæller · tæller, nævner · nævner.'],
  ['broek-div-direkte', 'broeker', 'Dividerer tæller med tæller',
    'At (a/b) : (c/d) = (a:c)/(b:d).',
    'Man dividerer med en brøk ved at gange med den omvendte.',
    'Vend den bagerste brøk om og gang.'],
  ['broek-stoerre-naevner', 'broeker', 'Stor nævner = stor brøk',
    'At 1/8 er større end 1/3, fordi 8 > 3.',
    'Jo flere stykker kagen deles i, jo mindre bliver hvert stykke.',
    'Større nævner, mindre stykke.'],
  ['broek-forkort-taeller', 'broeker', 'Forkorter kun i tælleren',
    'At man må dividere tælleren uden at dividere nævneren.',
    'Forkortning er at dividere tæller *og* nævner med det samme tal.',
    'Gør altid det samme oppe og nede.'],

  /* Decimaler */
  ['decimal-laengere-stoerre', 'decimaler', 'Flere cifre = større tal',
    'At 0,25 er større end 0,7.',
    'Man sammenligner pladsværdi for pladsværdi. Tiendedelene afgør først: 7 tiendedele slår 2 tiendedele.',
    'Sammenlign cifrene fra venstre — fyld op med nuller.'],
  ['decimal-komma', 'decimaler', 'Glemmer kommaet i gangestykket',
    'At 0,3 · 0,4 = 1,2.',
    'Antallet af decimaler i svaret er summen af decimalerne i de to faktorer.',
    '1 + 1 decimal = 2 decimaler: 0,3 · 0,4 = 0,12.'],
  ['decimal-gange-stoerre', 'decimaler', 'Gange gør altid tallet større',
    'At man ikke kan blive mindre af at gange.',
    'Ganger man med et tal mellem 0 og 1, bliver resultatet mindre.',
    '20 · 0,5 er det halve af 20.'],

  /* Procenter */
  ['procent-tilbage', 'procenter', 'Op og ned med samme procent',
    'At +20 % efterfulgt af −20 % giver det oprindelige tal.',
    'De to procenter regnes af forskellige grundtal, så man ender lavere end man startede.',
    '100 → +20 % → 120 → −20 % → 96.'],
  ['procent-grundtal', 'procenter', 'Regner af det forkerte tal',
    'At procenten altid tages af det nye tal.',
    'Procent regnes af det oprindelige beløb — grundtallet — medmindre opgaven siger andet.',
    'Spørg: procent af hvad?'],
  ['procent-laeg-sammen', 'procenter', 'Lægger procenter sammen',
    'At to stigninger på 10 % giver 20 %.',
    'Procenter ganges sammen som vækstfaktorer, de lægges ikke sammen.',
    '1,10 · 1,10 = 1,21 → 21 %.'],
  ['procentpoint', 'procenter', 'Procent og procentpoint',
    'At en stigning fra 20 % til 25 % er en stigning på 5 %.',
    'Det er 5 procent*point*. Den procentvise stigning er 5/20 = 25 %.',
    'Point = forskellen. Procent = forskellen delt med udgangspunktet.'],

  /* Forhold */
  ['forhold-omvendt', 'forhold', 'Omvendt proportionalitet',
    'At dobbelt så mange altid betyder dobbelt så meget.',
    'Ved omvendt proportionalitet er produktet konstant: flere arbejdere → kortere tid.',
    'Ligefrem: y/x fast. Omvendt: x·y fast.'],
  ['maalestok-vej', 'forhold', 'Målestok den forkerte vej',
    'At 1:100 betyder at tegningen er 100 gange større.',
    '1:100 betyder at 1 cm på tegningen svarer til 100 cm i virkeligheden.',
    'Tegning → virkelighed: gang. Virkelighed → tegning: divider.'],

  /* Potenser og rødder */
  ['potens-gang-eksponenter', 'potenser', 'Ganger eksponenterne',
    'At a³ · a² = a⁶.',
    'Når man ganger potenser med samme grundtal, lægger man eksponenterne sammen.',
    'a^m · a^n = a^(m+n)'],
  ['potens-nul', 'potenser', 'Noget i nulte',
    'At a⁰ = 0.',
    'a⁰ = 1 for alle a ≠ 0 — det følger af a^n : a^n = 1.',
    'Alt i nulte er 1.'],
  ['potens-base-gange', 'potenser', 'Ganger grundtal med eksponent',
    'At 2³ = 6.',
    'Eksponenten fortæller hvor mange gange grundtallet skal ganges med sig selv.',
    '2³ = 2 · 2 · 2 = 8.'],
  ['rod-halverer', 'roedder', 'Kvadratroden halverer',
    'At √16 = 8.',
    'Kvadratroden spørger: hvilket tal ganget med sig selv giver 16? Svaret er 4.',
    '√16 = 4, fordi 4 · 4 = 16.'],
  ['rod-sum', 'roedder', 'Roden af en sum',
    'At √(9 + 16) = 3 + 4.',
    'Kvadratroden kan ikke deles op over plus og minus. Regn først inde i roden.',
    '√(9+16) = √25 = 5, ikke 7.'],

  /* Algebra */
  ['algebra-uens-led', 'algebra', 'Lægger uens led sammen',
    'At 2x + 3 = 5x.',
    'Kun led med præcis samme variabeldel kan lægges sammen. x og tal er forskellige ting.',
    '2 æbler + 3 pærer er ikke 5 æbler.'],
  ['algebra-parentes-delvis', 'algebra', 'Ganger kun ind på det første led',
    'At 3(x + 4) = 3x + 4.',
    'Faktoren uden for parentesen skal ganges på *hvert* led inde i parentesen.',
    '3(x + 4) = 3x + 12.'],
  ['algebra-kvadrat-sum', 'algebra', 'Kvadrerer led for led',
    'At (a + b)² = a² + b².',
    'Der mangler det dobbelte produkt: (a+b)² = a² + 2ab + b².',
    'Husk 2ab i midten.'],
  ['algebra-minus-parentes', 'algebra', 'Minus foran parentes',
    'At −(x − 3) = −x − 3.',
    'Minus vender fortegnet på *alle* led i parentesen.',
    '−(x − 3) = −x + 3.'],

  /* Ligninger og uligheder */
  ['ligning-en-side', 'ligninger', 'Gør kun noget på den ene side',
    'At man kan fjerne et led uden at gøre det samme på begge sider.',
    'En ligning er en vægt i balance. Det du gør til venstre, skal du gøre til højre.',
    'Samme handling på begge sider — altid.'],
  ['ligning-fortegn', 'ligninger', 'Flytter led uden fortegnsskift',
    'At +4 stadig er +4 når det skifter side.',
    'At "flytte over" er i virkeligheden at trække fra på begge sider — derfor skifter fortegnet.',
    'Skifter side → skifter fortegn.'],
  ['ligning-divider-delvis', 'ligninger', 'Dividerer kun ét led',
    'At (2x + 6) : 2 = x + 6.',
    'Divisionen rammer hele siden, altså hvert eneste led.',
    '(2x + 6) : 2 = x + 3.'],
  ['ulighed-vend-glemt', 'uligheder', 'Glemmer at vende ulighedstegnet',
    'At tegnet bliver stående når man ganger eller dividerer med et negativt tal.',
    'Negative tal vender rækkefølgen på tallinjen, så tegnet skal vendes.',
    '−2x > 6  ⟹  x < −3.'],

  /* Geometri */
  ['vinkelsum-forkert', 'geometri', 'Forkert vinkelsum',
    'At vinklerne i en trekant giver 360°.',
    'En trekant har vinkelsum 180°. Det er firkanten der har 360°.',
    'Trekant 180°, firkant 360°.'],
  ['pythagoras-katete', 'geometri', 'Forveksler hypotenuse og katete',
    'At den længste side altid er den man skal finde.',
    'a² + b² = c² gælder kun med c som hypotenusen — siden over for den rette vinkel.',
    'Skal du finde en katete: c² − a² = b².'],
  ['pythagoras-uden-kvadrat', 'geometri', 'Lægger siderne sammen',
    'At c = a + b.',
    'Pythagoras handler om kvadraterne på siderne, ikke om siderne selv.',
    '3 + 4 = 7, men √(3² + 4²) = 5.'],
  ['ligedannet-plus', 'geometri', 'Lægger til i stedet for at gange',
    'At ligedannede figurer får lagt det samme tal til alle sider.',
    'Ligedannethed er en *skalering*: alle sider ganges med den samme faktor.',
    'Find skalafaktoren ved at dividere to ensliggende sider.'],

  /* Areal og rumfang */
  ['areal-omkreds', 'areal-rumfang', 'Forveksler areal og omkreds',
    'At areal og omkreds er samme slags tal.',
    'Omkreds er turen hele vejen rundt (cm). Areal er fladen indeni (cm²).',
    'Omkreds = hegnet. Areal = græsset.'],
  ['cirkel-areal-formel', 'areal-rumfang', 'Bruger omkredsformlen som areal',
    'At arealet af en cirkel er 2πr.',
    '2πr er omkredsen. Arealet er πr².',
    'Areal har r i anden — det passer med cm².'],
  ['rumfang-to-dimensioner', 'areal-rumfang', 'Glemmer den tredje dimension',
    'At rumfang kan findes med to mål.',
    'Rumfang måler noget rumligt og kræver tre mål — derfor cm³.',
    'Kasse: længde · bredde · højde.'],
  ['enhed-potens', 'areal-rumfang', 'Forkert enhed',
    'At areal måles i cm og rumfang i cm².',
    'Længde: cm. Areal: cm². Rumfang: cm³. Eksponenten svarer til antal dimensioner.',
    'Tæl dimensionerne — det er eksponenten.'],

  /* Koordinater og funktioner */
  ['koordinat-byttet', 'koordinatsystem', 'Bytter om på x og y',
    'At (3, 5) betyder 3 op og 5 hen.',
    'Første tal er altid x — vandret. Andet tal er y — lodret.',
    'Først hen ad gangen, så op ad trappen.'],
  ['haeldning-omvendt', 'funktioner', 'Vender hældningsbrøken om',
    'At hældningen er Δx/Δy.',
    'Hældningen er hvor meget y ændrer sig pr. 1 skridt hen ad x-aksen.',
    'a = Δy/Δx — "op divideret med hen".'],
  ['funktion-a-og-b', 'funktioner', 'Bytter om på a og b',
    'At b er hældningen i y = ax + b.',
    'a er hældningen; b er skæringen med y-aksen, altså værdien når x = 0.',
    'b står alene — derfor er den startværdien.'],
  ['eksponentiel-lineaer', 'funktioner', 'Behandler eksponentiel vækst som lineær',
    'At man lægger det samme til hver gang.',
    'Ved eksponentiel udvikling *ganges* der med den samme faktor hver gang.',
    'Lineær: +a. Eksponentiel: ·a.'],

  /* Statistik og sandsynlighed */
  ['median-usorteret', 'statistik', 'Finder median uden at sortere',
    'At medianen er det tal der står i midten af listen som den er skrevet.',
    'Tallene skal sorteres i rækkefølge først — ellers er "midten" tilfældig.',
    'Sortér → find midten.'],
  ['typetal-hyppighed', 'statistik', 'Angiver hyppigheden i stedet for værdien',
    'At typetallet er hvor mange gange tallet går igen.',
    'Typetallet er selve den værdi der optræder oftest.',
    'Typetal = værdien, ikke antallet.'],
  ['middel-median', 'statistik', 'Middeltal og median er det samme',
    'At de to altid giver samme resultat.',
    'Enkelte meget store eller små værdier trækker i middeltallet, men ikke i medianen.',
    'Skæve data → medianen fortæller mest.'],
  ['sandsyn-plus-gange', 'sandsynlighed', 'Lægger sandsynligheder sammen',
    'At to hændelser efter hinanden giver p₁ + p₂.',
    '"Og" betyder gange. "Eller" (uforenelige hændelser) betyder plus.',
    'Begge dele sker → gang.'],
  ['sandsyn-tilbagelaegning', 'sandsynlighed', 'Glemmer at antallet falder',
    'At sandsynligheden er den samme i anden træk uden tilbagelægning.',
    'Uden tilbagelægning er der én kugle færre i posen — både i tæller og nævner.',
    '2. træk: (n−1) i nævneren.'],
  ['sandsyn-over-1', 'sandsynlighed', 'Sandsynlighed over 1',
    'At et resultat over 1 (eller over 100 %) kan passe.',
    'En sandsynlighed ligger altid mellem 0 og 1. Får du mere, er der lagt sammen hvor der skulle ganges.',
    '0 ≤ p ≤ 1 — tjek altid til sidst.'],

  /* Trigonometri */
  ['trig-forkert-forhold', 'trigonometri', 'Vælger forkert forhold',
    'At det er ligegyldigt om man bruger sin, cos eller tan.',
    'Valget afhænger af hvilke to sider opgaven giver dig i forhold til vinklen.',
    'SOH-CAH-TOA.'],
  ['trig-hos-mod', 'trigonometri', 'Bytter om på hosliggende og modstående',
    'At den modstående katete er den man kan se ved siden af vinklen.',
    'Modstående ligger over for vinklen; hosliggende støder op til den.',
    'Peg fra vinklen — det du peger på, er modstående.'],

  /* Anvendelse */
  ['model-vaelg-forkert', 'modeller', 'Vælger forkert modeltype',
    'At al vækst kan beskrives med en ret linje.',
    'Faste kroner pr. gang → lineær. Fast procent pr. gang → eksponentiel.',
    'Spørg: lægges der til, eller ganges der?'],
  ['tekst-forkert-regneart', 'problemloesning', 'Griber den forkerte regneart',
    'At "i alt" altid betyder plus, og "forskel" altid minus.',
    'Signalordene hjælper, men du skal tegne eller skrive situationen op for at være sikker.',
    'Læs → skriv op → vælg → tjek om svaret er realistisk.'],
];

export const MISCONCEPTIONS: Misconception[] = defs.map(([id, domainId, name, belief, correction, tip]) => ({
  id,
  domainId,
  name,
  belief,
  correction,
  tip,
}));

const byId = new Map(MISCONCEPTIONS.map((m) => [m.id, m]));

export function getMisconception(id: string): Misconception | undefined {
  return byId.get(id);
}
