import type { CategoryId, DomainId, Skill } from '../types';

export const CATEGORY_SIGNATURES: Record<CategoryId, string> = {
  'tal-algebra': '\\dfrac{3}{4} = 75\\,\\%',
  'geometri-maaling': 'V = l \\cdot b \\cdot h',
  'statistik-sandsynlighed': 'P(6) = \\dfrac{1}{6}',
  kompetencer: 'y = 150 + 2x',
};

export const DOMAIN_SIGNATURES: Record<DomainId, string> = {
  tal: '3 + 4 \\cdot 2',
  broeker: '\\dfrac{3}{4}',
  decimaler: '0{,}25',
  procenter: '25\\,\\%',
  forhold: '2 : 3',
  potenser: '2^5',
  roedder: '\\sqrt{144}',
  algebra: 'a(b + c)',
  ligninger: '2x + 5 = 17',
  uligheder: 'x < 4',
  geometri: 'a^2 + b^2 = c^2',
  'areal-rumfang': 'A = \\pi r^2',
  trigonometri: '\\sin v',
  koordinatsystem: '(3,\\,-2)',
  flytninger: "P \\mapsto P'",
  tegning: '1 : 50',
  funktioner: 'y = ax + b',
  statistik: '\\bar{x} = 7',
  sandsynlighed: 'P = \\dfrac{1}{6}',
  problemloesning: '3, 7, 11, \\ldots',
  modeller: 'y = b \\cdot a^x',
};

const SKILL_SIGNATURES: Record<string, string> = {
  'algebra-udtryk': '3x + 2',
  'algebra-reducer': '5x + 3x = 8x',
  'algebra-parentes': '3(x + 4) = 3x + 12',
  'algebra-kvadratsaetninger': '(a + b)^2 = a^2 + 2ab + b^2',
  'algebra-faktorisering': '6x + 9 = 3(2x + 3)',
  'areal-omkreds': 'A = l \\cdot b',
  'areal-trekant': 'A = \\dfrac{1}{2} \\cdot h \\cdot g',
  'areal-cirkel': 'A = \\pi r^2',
  'areal-sammensat': 'A = A_1 + A_2',
  'rumfang-kasse': 'V = l \\cdot b \\cdot h',
  'rumfang-cylinder': 'V = \\pi r^2 h',
  'broek-forstaa': '\\dfrac{3}{4}',
  'broek-forkort': '\\dfrac{6}{8} = \\dfrac{3}{4}',
  'broek-plusminus': '\\dfrac{1}{2} + \\dfrac{1}{3} = \\dfrac{5}{6}',
  'broek-gange-dividere': '\\dfrac{2}{3} \\cdot \\dfrac{3}{4} = \\dfrac{1}{2}',
  'broek-omregning': '\\dfrac{1}{4} = 0{,}25 = 25\\,\\%',
  'decimal-pladsvaerdi': '0{,}5 > 0{,}45',
  'decimal-regning': '1{,}2 \\cdot 0{,}3 = 0{,}36',
  'decimal-tipotenser': '3{,}7 \\cdot 100 = 370',
  'flyt-symmetri': '360^\\circ : 4 = 90^\\circ',
  'flyt-koordinater': '(x, y) \\mapsto (x, -y)',
  'forhold-grund': '2 : 3 = 4 : 6',
  'forhold-proportional': 'y = k \\cdot x',
  'forhold-maalestok': '1 : 50',
  'funk-begreb': 'f(3) = 2 \\cdot 3 + 1',
  'funk-lineaer': 'y = ax + b',
  'funk-proportional': 'y = 4x',
  'funk-eksponentiel': 'y = b \\cdot a^x',
  'geo-vinkler': 'u + v = 180^\\circ',
  'geo-trekanter': 'A + B + C = 180^\\circ',
  'geo-firkanter': 'A + B + C + D = 360^\\circ',
  'geo-pythagoras': 'a^2 + b^2 = c^2',
  'geo-ligedannethed': "\\dfrac{a'}{a} = \\dfrac{b'}{b}",
  'koord-punkter': 'P(3,\\,-2)',
  'koord-afstand': 'd = \\sqrt{3^2 + 4^2}',
  'ligning-ettrin': 'x + 7 = 12',
  'ligning-totrin': '2x + 5 = 17',
  'ligning-begge-sider': '5x - 3 = 2x + 9',
  'ligning-parenteser': '3(x - 2) = 12',
  'ligning-formler': 'b = \\dfrac{A}{l}',
  'model-opstil': 'y = 150 + 2x',
  'model-vaelg': 'y = 80 \\cdot 1{,}05^x',
  'potens-grund': '2^5 = 32',
  'potens-regler': 'a^m \\cdot a^n = a^{m+n}',
  'potens-titalspotenser': '3{,}2 \\cdot 10^4',
  'prob-flertrin': '3 \\cdot 45 + 2 \\cdot 30',
  'prob-moenstre': '3, 7, 11, 15, \\ldots',
  'procent-af-tal': '25\\,\\% \\text{ af } 80 = 20',
  'procent-find-procenten': '\\dfrac{18}{24} = 75\\,\\%',
  'procent-aendring': '\\dfrac{60 - 50}{50} = 20\\,\\%',
  'procent-vaekstfaktor': '1{,}1 \\cdot 1{,}1 = 1{,}21',
  'rod-kvadratrod': '\\sqrt{144} = 12',
  'rod-regler': '\\sqrt{a \\cdot b} = \\sqrt{a} \\cdot \\sqrt{b}',
  'sand-grund': 'P = \\dfrac{1}{6}',
  'sand-kombineret': '\\dfrac{1}{2} \\cdot \\dfrac{1}{6} = \\dfrac{1}{12}',
  'stat-deskriptorer': '\\dfrac{4 + 7 + 10}{3} = 7',
  'stat-kvartiler': 'Q_1,\\ \\text{median},\\ Q_3',
  'stat-diagrammer': '\\dfrac{12}{40} = 30\\,\\%',
  'tal-regnearter': '156 : 12 = 13',
  'tal-hierarki': '3 + 4 \\cdot 2 = 11',
  'tal-negative': '-3 - 5 = -8',
  'tal-afrunding': '197 \\cdot 4 \\approx 800',
  'tal-primtal': '84 = 2^2 \\cdot 3 \\cdot 7',
  'tegn-former': '1 : 20',
  'tegn-maalfast': '4 \\text{ cm} \\cdot 50 = 2 \\text{ m}',
  'trig-forhold': '\\tan v = \\dfrac{\\text{mod}}{\\text{hos}}',
  'trig-find-side': 'a = c \\cdot \\sin A',
  'trig-find-vinkel': 'v = \\tan^{-1}(0{,}75)',
  'ulighed-grund': '2x + 1 < 9',
  'ulighed-negativ': '-2x < 6',
};

export function skillSignature(skill: Skill): string {
  return SKILL_SIGNATURES[skill.id] ?? DOMAIN_SIGNATURES[skill.domainId];
}

export function hasOwnSignature(skillId: string): boolean {
  return skillId in SKILL_SIGNATURES;
}
